// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { unstable_cache } from "next/cache";
import { createClient as createSupabaseClient } from "@supabase/supabase-js";
import { Suspense } from "react"; // 1. นำเข้า Suspense เพิ่มเข้ามาครับนาย

// Cache Navbar category data for 1 hour; product categories rarely change.
export const revalidate = 3600;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Terra Home Studio",
  description: "Generated by create next app",
};

type NavbarCollectionGroup = {
  product_sup: string | null;
  products: { id: string | number }[] | null;
};

const getCollectionsData = unstable_cache(
  async (): Promise<NavbarCollectionGroup[]> => {
    try {
      const supabase = createSupabaseClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
      );

      const { data, error } = await supabase
        .from("collection_groups")
        .select(`
          product_sup,
          products ( id )
        `);

      if (error) {
        console.error("Navbar Supabase error:", error.message);
        return [];
      }

      const activeData = ((data ?? []) as NavbarCollectionGroup[]).filter(
        (item) => item.products && item.products.length > 0
      );

      console.log("Navbar cached categories count:", activeData.length);
      return activeData;
    } catch (error) {
      console.error("Navbar data cache error:", error);
      return [];
    }
  },
  ["navbar-collection-groups"],
  { revalidate: 3600 }
);

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const collections = await getCollectionsData();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* 2. ห่อหุ้ม Navbar ด้วย Suspense เพื่อให้ฝั่ง Client สามารถดึง searchParams มาใช้ได้ตอน build */}
        <Suspense fallback={<div className="h-20 bg-[#F9F6F0] w-full animate-pulse" />}>
          <Navbar collections={collections} />
        </Suspense>
        
        <main className="flex-1 w-full">
          {/* 3. ห่อ children เผื่อหน้า _not-found หรือหน้าอื่นแอบเรียกใช้ searchParams ด้วยครับ */}
          <Suspense fallback={
            <div className="min-h-screen bg-[#F9F6F0] flex items-center justify-center font-serif text-[#4A3E3D]">
              Loading...
            </div>
          }>
            {children}
          </Suspense>
        </main>
      </body>
    </html>
  );
}